server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: airflow-task-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: airflow-task-logs
          service: airflow
          __path__: /workspace/airflow/logs/**/*.log
