\connect airflow
ALTER DATABASE airflow OWNER TO airflow;
ALTER SCHEMA public OWNER TO airflow;
GRANT ALL ON SCHEMA public TO airflow;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO airflow;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO airflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO airflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO airflow;

\connect galaxy_app
ALTER DATABASE galaxy_app OWNER TO galaxy;
ALTER SCHEMA public OWNER TO galaxy;
GRANT ALL ON SCHEMA public TO galaxy;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO galaxy;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO galaxy;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO galaxy;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO galaxy;

\connect mlflow
ALTER DATABASE mlflow OWNER TO mlflow;
ALTER SCHEMA public OWNER TO mlflow;
GRANT ALL ON SCHEMA public TO mlflow;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mlflow;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mlflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO mlflow;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO mlflow;